twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        mailer_contact: '%mailer_contact%'
        mailer_from: '%mailer_from%'
        mailer_from_name: '%mailer_from_name%'
        navigation: '@App\Service\FrontNavigation'

when@test:
    twig:
        strict_variables: true
