vich_uploader:
    db_driver: orm

    mappings:
        orders:
            uri_prefix: /files/orders
            upload_destination: '%kernel.project_dir%/public/files/orders'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
