vich_uploader:
    db_driver: orm

    mappings:
        orders:
            uri_prefix: /files/orders
            upload_destination: '%order_file_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
